management:
  security:
    enabled: false
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

bucket4j:
  rate-limit:
    enabled: true
    configs:
    - cache-name: buckets
      filter-type: default
      url: /*
      bandwidths: 
      -
        capacity: 5
        time: 10
        unit: seconds  
    - cache-name: buckets
      filter-type: ip
      url: /*
      bandwidths: 
      -
        capacity: 5
        time: 10
        unit: seconds
    - cache-name: buckets
      filter-type: expression
      expression: getRemoteAddr()
      url: /*
      bandwidths: 
      -
        capacity: 5
        time: 10
        unit: seconds               
          