management:
  security:
    enabled: false
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  rate-limit:
    enabled: true
    configs:
    - cache-name: buckets
      filter-type: expression
      expression: "@securityService.username()?: getRemoteAddr()"
      url: /*
      filter-order: 0
      bandwidths: 
      -
        capacity: 20
        time: 1
        unit: minutes               
          